name: Publish

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: dragoness.es
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "build/"
          strip_components: 1
          target: "${{ secrets.SSH_REMOTE_DIR }}"